obj-y += translate.o dsp_helper.o op_helper.o lmi_helper.o helper.o cpu.o
obj-y += cache_helper.o mips-cache-opts.o cache.o
obj-y += replacement_lru.o replacement_lfu.o replacement_rnd.o
obj-y += gnuplot_i.o
obj-y += gdbstub.o
obj-$(CONFIG_SOFTMMU) += machine.o
